// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/tuwaiq-devices/TuwaiqDevices.tsx": () => import("../components/mockups/tuwaiq-devices/TuwaiqDevices.tsx"),
  "./components/mockups/tuwaiq-promo/PromoPage.tsx": () => import("../components/mockups/tuwaiq-promo/PromoPage.tsx")
};
