// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/donate-page/ImpactStatement.tsx": () => import("../components/mockups/donate-page/ImpactStatement.tsx"),
  "./components/mockups/donate-page/SpiritualJourney.tsx": () => import("../components/mockups/donate-page/SpiritualJourney.tsx")
};
